import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type Language = 'fr' | 'en' | 'es' | 'de' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isTransitioning: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.install': 'Installer',
    'nav.login': 'Connexion',
    'nav.profile': 'Profil',
    'nav.admin': 'Administration',
    'nav.logout': 'Déconnexion',
    
    // Auth Modal
    'auth.title': 'Connexion',
    'auth.subtitle': 'Connectez-vous ou inscrivez-vous avec Discord',
    'auth.description': 'Accédez à votre profil et gérez vos messages',
    'auth.discord_button': 'Connexion par Discord',
    'auth.loading': 'Connexion en cours...',
    
    // Hero
    'hero.title': 'WifiRic',
    'hero.subtitle': 'Créateur Digital',
    'hero.text1': 'Sites Internet adaptés à vos besoins et à vos moyens financiers',
    'hero.text2': 'Bots Discord personnalisés selon vos besoins',
    'hero.text3': 'Expériences Digitales Uniques',
    'hero.description': 'Nous créons des sites internet ou bots discord selon vos besoins !',
    'hero.description2': 'Des sites web modernes ou anciens aux bots Discord complexes, nous transformons vos idées en réalité.',
    'hero.discord_button': 'Rejoindre notre Discord',
    'hero.services_button': 'Découvrir nos services',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Des solutions digitales complètes pour transformer votre présence en ligne',
    'services.web.title': 'Sites Web',
    'services.web.description': 'Développement Full-Stack de sites internet (Front-End et Back-End).',
    'services.bot.title': 'Bots Discord',
    'services.bot.description': 'Création de bots Discord personnalisés pour automatiser et enrichir votre communauté.',
    'services.design.title': 'Design UI/UX',
    'services.design.description': 'Interfaces utilisateur élégantes avec animations et micro-interactions et site sécurisées et optimisées pour garantir une meilleur expériences utilisateur',
    'services.cost.title': 'Coût',
    'services.cost.description': 'Des tarifs adaptés à vos besoins, avec des prix avantageux pour tous vos projets.',
    
    // Reviews
    'reviews.title': 'Nos Avis',
    'reviews.subtitle': 'Ce que nos clients disent de notre travail',
    'reviews.filters': 'Filtres',
    'reviews.filter_rating': 'Filtrer par note',
    'reviews.filter_all': 'Toutes les notes',
    'reviews.filter_type': 'Filtrer par type de projet',
    'reviews.all_types': 'Tous les types',
    'reviews.website': 'Site Internet',
    'reviews.discord_bot': 'Bot Discord',
    'reviews.other': 'Autre',
    'reviews.clear_filters': 'Réinitialiser les filtres',
    'reviews.no_reviews': 'Aucun avis pour le moment',
    'reviews.no_matching': 'Aucun avis ne correspond aux filtres sélectionnés',
    'reviews.be_first': 'Soyez le premier à laisser un avis !',
    'reviews.leave_review': 'Laissez un avis',
    'reviews.login_required': 'Connectez-vous pour laisser un avis',
    'reviews.translate': 'Traduire',
    'reviews.translation_error': 'Erreur de traduction',
    
    // About
    'about.title': 'WifiRic - Notre Vision',
    'about.subtitle': 'Chez WifiRic, nous repoussons les limites du développement pour créer des expériences exceptionnelles qui marquent l\'avenir du web et des communautés Discord.',
    'about.web.title': 'Développement Web',
    'about.web.description': 'Des sites web adaptés à vos besoins et à vos demandes, pour donner vie à tout ce que vous imaginez.',
    'about.bot.title': 'Bots Discord',
    'about.bot.description': 'Automatisation et fonctionnalités personnalisées pour votre communauté.',
    'about.design.title': 'Design Futuriste',
    'about.design.description': 'Interfaces utilisateur élégantes avec animations et micro-interactions et site sécurisées et optimisées pour garantir une meilleur expériences utilisateur',
    'about.cost.title': 'Coût',
    'about.cost.description': 'Des tarifs adaptés à vos besoins, avec des prix avantageux pour tous vos projets.',
    'about.cta.title': 'Prêt à transformer votre projet ?',
    'about.cta.subtitle': 'Rejoignez notre communauté Discord et découvrez comment nous pouvons vous aider à créer quelque chose d\'extraordinaire.',
    'about.cta.button': 'Démarrer maintenant',
    
    // FAQ
    'faq.title': 'Questions Fréquentes',
    'faq.subtitle': 'Trouvez rapidement les réponses à vos questions',
    'faq.q1': 'Quels types de sites web créez-vous ?',
    'faq.a1': '//',
    'faq.q2': 'Combien coûte un site internet ou un bot Discord ?',
    'faq.a2': '//',
    'faq.q3': 'Quel est le délai de réalisation ?',
    'faq.a3': '//',
    'faq.q4': 'Proposez-vous de la maintenance ?',
    'faq.a4': '//',
    'faq.q5': 'Comment fonctionnent la création de bots Discord ?',
    'faq.a5': '//',
    'faq.q6': 'Acceptez-vous les paiements en plusieurs fois ?',
    'faq.a6': '//',
    'faq.no_answer': 'Vous ne trouvez pas votre réponse ?',
    'faq.no_answer_subtitle': 'Notre équipe est là pour répondre à toutes vos questions spécifiques',
    'faq.contact_discord': 'Contactez-nous sur Discord',
    
    // Contact
    'contact.title': 'Contactez-Nous',
    'contact.subtitle': 'Prêt à démarrer votre projet ? Nous sommes là pour vous accompagner',
    'contact.methods': 'Méthodes de Contact',
    'contact.discord_recommended': 'Discord (Recommandé)',
    'contact.discord_desc': 'Rejoignez notre serveur pour un support instantané',
    'contact.email': 'Email',
    'contact.email_desc': 'Utilisez le formulaire ci-contre',
    'contact.why_choose': 'Pourquoi choisir WifiRic ?',
    'contact.benefit1': 'Support réactif et personnalisé',
    'contact.benefit2': 'Technologies de pointe',
    'contact.benefit3': 'Satisfaction client garantie',
    'contact.pricing': 'Tarifs ?',
    'contact.pricing1': 'Le devis de votre Site Internet/Bot Discord sera gratuit.',
    'contact.pricing2': 'En fonction de votre demande, le tarif sera adapté.',
    'contact.form.name': 'Nom',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Sujet',
    'contact.form.message': 'Message',
    'contact.form.project_type': 'Type de projet',
    'contact.form.website': 'Site Internet',
    'contact.form.discord_bot': 'Bot Discord',
    'contact.form.both': 'Les deux',
    'contact.form.other': 'Autre',
    'contact.form.submit': 'Envoyer le message',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.success': 'Demande envoyée avec succès !',
    'contact.form.success_desc': 'Nous vous répondrons dans les 48h sur notre Discord : WifiRic',
    'contact.form.error': 'Erreur',
    'contact.form.error_desc': 'Erreur lors de l\'envoi du message. Veuillez réessayer.',
    'contact.login_required': 'Connexion Requise',
    'contact.login_desc': 'Veuillez vous connecter avec votre compte Discord pour envoyer un message',
    'contact.login_button': 'Connexion avec Discord',
    'contact.back': 'Retour',
    'contact.validation.name': 'Le nom est requis',
    'contact.validation.email': 'L\'email est requis',
    'contact.validation.email_invalid': 'Email invalide',
    'contact.validation.subject': 'Le sujet est requis',
    'contact.validation.message': 'Le message est requis',
    
    // Install
    'install.title': 'Installer',
    'install.subtitle': 'Ajoutez WifiRic à votre écran d\'accueil pour une expérience optimale, comme une vraie application native.',
    'install.installed': 'Application installée !',
    'install.installed_desc': 'WifiRic est déjà installé sur votre appareil. Retrouvez-le sur votre écran d\'accueil.',
    'install.back_home': 'Retour à l\'accueil',
    'install.quick_install': 'Installation rapide disponible',
    'install.quick_install_desc': 'Votre navigateur supporte l\'installation automatique. Cliquez pour installer en un clic !',
    'install.install_now': 'Installer maintenant',
    'install.why_install': 'Pourquoi installer l\'app ?',
    'install.benefit1.title': 'Chargement instantané',
    'install.benefit1.desc': 'L\'app se lance en une fraction de seconde, sans attendre le navigateur.',
    'install.benefit2.title': 'Mode hors-ligne',
    'install.benefit2.desc': 'Accédez aux pages déjà visitées même sans connexion internet.',
    'install.benefit3.title': 'Notifications',
    'install.benefit3.desc': 'Recevez des alertes sur les nouveautés et mises à jour importantes.',
    'install.benefit4.title': 'Sécurisé',
    'install.benefit4.desc': 'Connexion HTTPS et données protégées comme sur le site web.',
    'install.guide': 'Guide d\'installation',
    'install.android': 'Android',
    'install.ios': 'iPhone / iPad',
    'install.detected': 'Détecté :',
    'install.device_ios': 'Appareil iOS (iPhone/iPad)',
    'install.device_android': 'Appareil Android',
    'install.instructions_shown': '- Les instructions correspondantes sont affichées ci-dessous.',
    'install.android.step1.title': 'Ouvrez Chrome',
    'install.android.step1.desc': 'Assurez-vous d\'être sur Chrome ou un navigateur compatible.',
    'install.android.step2.title': 'Menu du navigateur',
    'install.android.step2.desc': 'Appuyez sur les trois points en haut à droite du navigateur.',
    'install.android.step3.title': 'Installer l\'application',
    'install.android.step3.desc': 'Sélectionnez "Installer l\'application" ou "Ajouter à l\'écran d\'accueil".',
    'install.android.step4.title': 'Confirmer',
    'install.android.step4.desc': 'Appuyez sur "Installer" dans la boîte de dialogue qui apparaît.',
    'install.android.tip': 'Astuce',
    'install.android.tip_desc': 'Si vous voyez une bannière "Ajouter WifiRic à l\'écran d\'accueil" en bas de l\'écran, appuyez dessus pour une installation encore plus rapide !',
    'install.ios.step1.title': 'Ouvrez Safari',
    'install.ios.step1.desc': 'L\'installation PWA ne fonctionne qu\'avec Safari sur iOS.',
    'install.ios.step2.title': 'Bouton Partager',
    'install.ios.step2.desc': 'Appuyez sur l\'icône de partage en bas de l\'écran (carré avec flèche).',
    'install.ios.step3.title': 'Sur l\'écran d\'accueil',
    'install.ios.step3.desc': 'Faites défiler et appuyez sur "Sur l\'écran d\'accueil".',
    'install.ios.step4.title': 'Ajouter',
    'install.ios.step4.desc': 'Appuyez sur "Ajouter" en haut à droite pour confirmer.',
    'install.ios.important': 'Important pour iOS',
    'install.ios.important_desc': 'L\'installation sur iPhone et iPad nécessite obligatoirement Safari. Chrome, Firefox et autres navigateurs ne supportent pas cette fonctionnalité sur iOS.',
    
    // Footer
    'footer.description': 'Création de sites internet modernes et de bots Discord personnalisés. Nous transformons vos idées en expériences digitales exceptionnelles.',
    'footer.quick_links': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.copyright': 'Copyright ©2025 WifiRic. Conçu par Nathan & Aymeric',
    'footer.support': 'Support',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions générales',
    
    // Language
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.de': 'Deutsch',
    'language.pt': 'Português',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.install': 'Install',
    'nav.login': 'Login',
    'nav.profile': 'Profile',
    'nav.admin': 'Administration',
    'nav.logout': 'Logout',
    
    // Auth Modal
    'auth.title': 'Login',
    'auth.subtitle': 'Sign in or sign up with Discord',
    'auth.description': 'Access your profile and manage your messages',
    'auth.discord_button': 'Login with Discord',
    'auth.loading': 'Signing in...',
    
    // Hero
    'hero.title': 'WifiRic',
    'hero.subtitle': 'Digital Creator',
    'hero.text1': 'Websites tailored to your needs and budget',
    'hero.text2': 'Custom Discord bots for your needs',
    'hero.text3': 'Unique Digital Experiences',
    'hero.description': 'We create websites or Discord bots according to your needs!',
    'hero.description2': 'From modern or classic websites to complex Discord bots, we turn your ideas into reality.',
    'hero.discord_button': 'Join our Discord',
    'hero.services_button': 'Discover our services',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Complete digital solutions to transform your online presence',
    'services.web.title': 'Websites',
    'services.web.description': 'Full-Stack website development (Front-End and Back-End).',
    'services.bot.title': 'Discord Bots',
    'services.bot.description': 'Creation of custom Discord bots to automate and enrich your community.',
    'services.design.title': 'UI/UX Design',
    'services.design.description': 'Elegant user interfaces with animations and micro-interactions, secure and optimized sites for the best user experience',
    'services.cost.title': 'Cost',
    'services.cost.description': 'Rates tailored to your needs, with competitive prices for all your projects.',
    
    // Reviews
    'reviews.title': 'Our Reviews',
    'reviews.subtitle': 'What our clients say about our work',
    'reviews.filters': 'Filters',
    'reviews.filter_rating': 'Filter by rating',
    'reviews.filter_all': 'All ratings',
    'reviews.filter_type': 'Filter by project type',
    'reviews.all_types': 'All types',
    'reviews.website': 'Website',
    'reviews.discord_bot': 'Discord Bot',
    'reviews.other': 'Other',
    'reviews.clear_filters': 'Clear filters',
    'reviews.no_reviews': 'No reviews yet',
    'reviews.no_matching': 'No reviews match the selected filters',
    'reviews.be_first': 'Be the first to leave a review!',
    'reviews.leave_review': 'Leave a review',
    'reviews.login_required': 'Login to leave a review',
    'reviews.translate': 'Translate',
    'reviews.translation_error': 'Translation error',
    
    // About
    'about.title': 'WifiRic - Our Vision',
    'about.subtitle': 'At WifiRic, we push the boundaries of development to create exceptional experiences that shape the future of the web and Discord communities.',
    'about.web.title': 'Web Development',
    'about.web.description': 'Websites tailored to your needs and requests, to bring everything you imagine to life.',
    'about.bot.title': 'Discord Bots',
    'about.bot.description': 'Automation and custom features for your community.',
    'about.design.title': 'Futuristic Design',
    'about.design.description': 'Elegant user interfaces with animations and micro-interactions, secure and optimized sites for the best user experience',
    'about.cost.title': 'Cost',
    'about.cost.description': 'Rates tailored to your needs, with competitive prices for all your projects.',
    'about.cta.title': 'Ready to transform your project?',
    'about.cta.subtitle': 'Join our Discord community and discover how we can help you create something extraordinary.',
    'about.cta.button': 'Get started now',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Quickly find answers to your questions',
    'faq.q1': 'What types of websites do you create?',
    'faq.a1': '//',
    'faq.q2': 'How much does a website or Discord bot cost?',
    'faq.a2': '//',
    'faq.q3': 'What is the delivery time?',
    'faq.a3': '//',
    'faq.q4': 'Do you offer maintenance?',
    'faq.a4': '//',
    'faq.q5': 'How does Discord bot creation work?',
    'faq.a5': '//',
    'faq.q6': 'Do you accept installment payments?',
    'faq.a6': '//',
    'faq.no_answer': 'Can\'t find your answer?',
    'faq.no_answer_subtitle': 'Our team is here to answer all your specific questions',
    'faq.contact_discord': 'Contact us on Discord',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to start your project? We\'re here to help',
    'contact.methods': 'Contact Methods',
    'contact.discord_recommended': 'Discord (Recommended)',
    'contact.discord_desc': 'Join our server for instant support',
    'contact.email': 'Email',
    'contact.email_desc': 'Use the form below',
    'contact.why_choose': 'Why choose WifiRic?',
    'contact.benefit1': 'Responsive and personalized support',
    'contact.benefit2': 'Cutting-edge technologies',
    'contact.benefit3': 'Guaranteed customer satisfaction',
    'contact.pricing': 'Pricing?',
    'contact.pricing1': 'Your Website/Discord Bot quote will be free.',
    'contact.pricing2': 'Based on your request, the price will be adjusted.',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.project_type': 'Project Type',
    'contact.form.website': 'Website',
    'contact.form.discord_bot': 'Discord Bot',
    'contact.form.both': 'Both',
    'contact.form.other': 'Other',
    'contact.form.submit': 'Send message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Request sent successfully!',
    'contact.form.success_desc': 'We will respond within 48 hours on our Discord: WifiRic',
    'contact.form.error': 'Error',
    'contact.form.error_desc': 'Error sending message. Please try again.',
    'contact.login_required': 'Login Required',
    'contact.login_desc': 'Please log in with your Discord account to send a message',
    'contact.login_button': 'Login with Discord',
    'contact.back': 'Back',
    'contact.validation.name': 'Name is required',
    'contact.validation.email': 'Email is required',
    'contact.validation.email_invalid': 'Invalid email',
    'contact.validation.subject': 'Subject is required',
    'contact.validation.message': 'Message is required',
    
    // Install
    'install.title': 'Install',
    'install.subtitle': 'Add WifiRic to your home screen for an optimal experience, like a real native app.',
    'install.installed': 'App installed!',
    'install.installed_desc': 'WifiRic is already installed on your device. Find it on your home screen.',
    'install.back_home': 'Back to home',
    'install.quick_install': 'Quick install available',
    'install.quick_install_desc': 'Your browser supports automatic installation. Click to install in one click!',
    'install.install_now': 'Install now',
    'install.why_install': 'Why install the app?',
    'install.benefit1.title': 'Instant loading',
    'install.benefit1.desc': 'The app launches in a fraction of a second, without waiting for the browser.',
    'install.benefit2.title': 'Offline mode',
    'install.benefit2.desc': 'Access previously visited pages even without internet connection.',
    'install.benefit3.title': 'Notifications',
    'install.benefit3.desc': 'Receive alerts about news and important updates.',
    'install.benefit4.title': 'Secure',
    'install.benefit4.desc': 'HTTPS connection and protected data just like on the website.',
    'install.guide': 'Installation Guide',
    'install.android': 'Android',
    'install.ios': 'iPhone / iPad',
    'install.detected': 'Detected:',
    'install.device_ios': 'iOS Device (iPhone/iPad)',
    'install.device_android': 'Android Device',
    'install.instructions_shown': '- Corresponding instructions are shown below.',
    'install.android.step1.title': 'Open Chrome',
    'install.android.step1.desc': 'Make sure you\'re using Chrome or a compatible browser.',
    'install.android.step2.title': 'Browser menu',
    'install.android.step2.desc': 'Tap the three dots in the top right of the browser.',
    'install.android.step3.title': 'Install app',
    'install.android.step3.desc': 'Select "Install app" or "Add to Home screen".',
    'install.android.step4.title': 'Confirm',
    'install.android.step4.desc': 'Tap "Install" in the dialog that appears.',
    'install.android.tip': 'Tip',
    'install.android.tip_desc': 'If you see a banner "Add WifiRic to Home screen" at the bottom, tap it for an even faster installation!',
    'install.ios.step1.title': 'Open Safari',
    'install.ios.step1.desc': 'PWA installation only works with Safari on iOS.',
    'install.ios.step2.title': 'Share button',
    'install.ios.step2.desc': 'Tap the share icon at the bottom of the screen (square with arrow).',
    'install.ios.step3.title': 'Add to Home Screen',
    'install.ios.step3.desc': 'Scroll down and tap "Add to Home Screen".',
    'install.ios.step4.title': 'Add',
    'install.ios.step4.desc': 'Tap "Add" in the top right to confirm.',
    'install.ios.important': 'Important for iOS',
    'install.ios.important_desc': 'Installation on iPhone and iPad requires Safari. Chrome, Firefox and other browsers do not support this feature on iOS.',
    
    // Footer
    'footer.description': 'Creating modern websites and custom Discord bots. We transform your ideas into exceptional digital experiences.',
    'footer.quick_links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.copyright': 'Copyright ©2025 WifiRic. Designed by Nathan & Aymeric',
    'footer.support': 'Support',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // Language
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.de': 'Deutsch',
    'language.pt': 'Português',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacto',
    'nav.install': 'Instalar',
    'nav.login': 'Iniciar sesión',
    'nav.profile': 'Perfil',
    'nav.admin': 'Administración',
    'nav.logout': 'Cerrar sesión',
    
    // Auth Modal
    'auth.title': 'Iniciar sesión',
    'auth.subtitle': 'Inicia sesión o regístrate con Discord',
    'auth.description': 'Accede a tu perfil y gestiona tus mensajes',
    'auth.discord_button': 'Iniciar sesión con Discord',
    'auth.loading': 'Conectando...',
    
    // Hero
    'hero.title': 'WifiRic',
    'hero.subtitle': 'Creador Digital',
    'hero.text1': 'Sitios web adaptados a tus necesidades y presupuesto',
    'hero.text2': 'Bots de Discord personalizados según tus necesidades',
    'hero.text3': 'Experiencias Digitales Únicas',
    'hero.description': '¡Creamos sitios web o bots de Discord según tus necesidades!',
    'hero.description2': 'Desde sitios web modernos o clásicos hasta bots de Discord complejos, convertimos tus ideas en realidad.',
    'hero.discord_button': 'Únete a nuestro Discord',
    'hero.services_button': 'Descubrir nuestros servicios',
    
    // Services
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones digitales completas para transformar tu presencia en línea',
    'services.web.title': 'Sitios Web',
    'services.web.description': 'Desarrollo Full-Stack de sitios web (Front-End y Back-End).',
    'services.bot.title': 'Bots Discord',
    'services.bot.description': 'Creación de bots de Discord personalizados para automatizar y enriquecer tu comunidad.',
    'services.design.title': 'Diseño UI/UX',
    'services.design.description': 'Interfaces de usuario elegantes con animaciones y micro-interacciones, sitios seguros y optimizados para la mejor experiencia de usuario',
    'services.cost.title': 'Costo',
    'services.cost.description': 'Tarifas adaptadas a tus necesidades, con precios competitivos para todos tus proyectos.',
    
    // Reviews
    'reviews.title': 'Nuestras Reseñas',
    'reviews.subtitle': 'Lo que nuestros clientes dicen de nuestro trabajo',
    'reviews.filters': 'Filtros',
    'reviews.filter_rating': 'Filtrar por calificación',
    'reviews.filter_all': 'Todas las calificaciones',
    'reviews.filter_type': 'Filtrar por tipo de proyecto',
    'reviews.all_types': 'Todos los tipos',
    'reviews.website': 'Sitio Web',
    'reviews.discord_bot': 'Bot Discord',
    'reviews.other': 'Otro',
    'reviews.clear_filters': 'Limpiar filtros',
    'reviews.no_reviews': 'Sin reseñas aún',
    'reviews.no_matching': 'Ninguna reseña coincide con los filtros seleccionados',
    'reviews.be_first': '¡Sé el primero en dejar una reseña!',
    'reviews.leave_review': 'Dejar una reseña',
    'reviews.login_required': 'Inicia sesión para dejar una reseña',
    'reviews.translate': 'Traducir',
    'reviews.translation_error': 'Error de traducción',
    
    // About
    'about.title': 'WifiRic - Nuestra Visión',
    'about.subtitle': 'En WifiRic, superamos los límites del desarrollo para crear experiencias excepcionales que marcan el futuro de la web y las comunidades de Discord.',
    'about.web.title': 'Desarrollo Web',
    'about.web.description': 'Sitios web adaptados a tus necesidades y solicitudes, para dar vida a todo lo que imaginas.',
    'about.bot.title': 'Bots Discord',
    'about.bot.description': 'Automatización y funciones personalizadas para tu comunidad.',
    'about.design.title': 'Diseño Futurista',
    'about.design.description': 'Interfaces de usuario elegantes con animaciones y micro-interacciones, sitios seguros y optimizados para la mejor experiencia de usuario',
    'about.cost.title': 'Costo',
    'about.cost.description': 'Tarifas adaptadas a tus necesidades, con precios competitivos para todos tus proyectos.',
    'about.cta.title': '¿Listo para transformar tu proyecto?',
    'about.cta.subtitle': 'Únete a nuestra comunidad de Discord y descubre cómo podemos ayudarte a crear algo extraordinario.',
    'about.cta.button': 'Comenzar ahora',
    
    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Encuentra rápidamente respuestas a tus preguntas',
    'faq.q1': '¿Qué tipos de sitios web crean?',
    'faq.a1': '//',
    'faq.q2': '¿Cuánto cuesta un sitio web o un bot de Discord?',
    'faq.a2': '//',
    'faq.q3': '¿Cuál es el tiempo de entrega?',
    'faq.a3': '//',
    'faq.q4': '¿Ofrecen mantenimiento?',
    'faq.a4': '//',
    'faq.q5': '¿Cómo funciona la creación de bots de Discord?',
    'faq.a5': '//',
    'faq.q6': '¿Aceptan pagos a plazos?',
    'faq.a6': '//',
    'faq.no_answer': '¿No encuentras tu respuesta?',
    'faq.no_answer_subtitle': 'Nuestro equipo está aquí para responder todas tus preguntas específicas',
    'faq.contact_discord': 'Contáctanos en Discord',
    
    // Contact
    'contact.title': 'Contáctanos',
    'contact.subtitle': '¿Listo para comenzar tu proyecto? Estamos aquí para ayudarte',
    'contact.methods': 'Métodos de Contacto',
    'contact.discord_recommended': 'Discord (Recomendado)',
    'contact.discord_desc': 'Únete a nuestro servidor para soporte instantáneo',
    'contact.email': 'Email',
    'contact.email_desc': 'Usa el formulario de abajo',
    'contact.why_choose': '¿Por qué elegir WifiRic?',
    'contact.benefit1': 'Soporte receptivo y personalizado',
    'contact.benefit2': 'Tecnologías de vanguardia',
    'contact.benefit3': 'Satisfacción del cliente garantizada',
    'contact.pricing': '¿Precios?',
    'contact.pricing1': 'El presupuesto de tu Sitio Web/Bot Discord será gratuito.',
    'contact.pricing2': 'Según tu solicitud, el precio se ajustará.',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.project_type': 'Tipo de proyecto',
    'contact.form.website': 'Sitio Web',
    'contact.form.discord_bot': 'Bot Discord',
    'contact.form.both': 'Ambos',
    'contact.form.other': 'Otro',
    'contact.form.submit': 'Enviar mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Solicitud enviada con éxito!',
    'contact.form.success_desc': 'Te responderemos en 48 horas en nuestro Discord: WifiRic',
    'contact.form.error': 'Error',
    'contact.form.error_desc': 'Error al enviar el mensaje. Por favor, inténtalo de nuevo.',
    'contact.login_required': 'Inicio de sesión requerido',
    'contact.login_desc': 'Por favor, inicia sesión con tu cuenta de Discord para enviar un mensaje',
    'contact.login_button': 'Iniciar sesión con Discord',
    'contact.back': 'Volver',
    'contact.validation.name': 'El nombre es requerido',
    'contact.validation.email': 'El email es requerido',
    'contact.validation.email_invalid': 'Email inválido',
    'contact.validation.subject': 'El asunto es requerido',
    'contact.validation.message': 'El mensaje es requerido',
    
    // Install
    'install.title': 'Instalar',
    'install.subtitle': 'Añade WifiRic a tu pantalla de inicio para una experiencia óptima, como una aplicación nativa real.',
    'install.installed': '¡App instalada!',
    'install.installed_desc': 'WifiRic ya está instalado en tu dispositivo. Encuéntralo en tu pantalla de inicio.',
    'install.back_home': 'Volver al inicio',
    'install.quick_install': 'Instalación rápida disponible',
    'install.quick_install_desc': 'Tu navegador soporta la instalación automática. ¡Haz clic para instalar en un clic!',
    'install.install_now': 'Instalar ahora',
    'install.why_install': '¿Por qué instalar la app?',
    'install.benefit1.title': 'Carga instantánea',
    'install.benefit1.desc': 'La app se inicia en una fracción de segundo, sin esperar al navegador.',
    'install.benefit2.title': 'Modo sin conexión',
    'install.benefit2.desc': 'Accede a las páginas visitadas anteriormente incluso sin conexión a internet.',
    'install.benefit3.title': 'Notificaciones',
    'install.benefit3.desc': 'Recibe alertas sobre novedades y actualizaciones importantes.',
    'install.benefit4.title': 'Seguro',
    'install.benefit4.desc': 'Conexión HTTPS y datos protegidos como en el sitio web.',
    'install.guide': 'Guía de instalación',
    'install.android': 'Android',
    'install.ios': 'iPhone / iPad',
    'install.detected': 'Detectado:',
    'install.device_ios': 'Dispositivo iOS (iPhone/iPad)',
    'install.device_android': 'Dispositivo Android',
    'install.instructions_shown': '- Las instrucciones correspondientes se muestran a continuación.',
    'install.android.step1.title': 'Abre Chrome',
    'install.android.step1.desc': 'Asegúrate de estar usando Chrome o un navegador compatible.',
    'install.android.step2.title': 'Menú del navegador',
    'install.android.step2.desc': 'Toca los tres puntos en la esquina superior derecha del navegador.',
    'install.android.step3.title': 'Instalar app',
    'install.android.step3.desc': 'Selecciona "Instalar app" o "Añadir a la pantalla de inicio".',
    'install.android.step4.title': 'Confirmar',
    'install.android.step4.desc': 'Toca "Instalar" en el diálogo que aparece.',
    'install.android.tip': 'Consejo',
    'install.android.tip_desc': 'Si ves un banner "Añadir WifiRic a la pantalla de inicio" en la parte inferior, ¡tócalo para una instalación aún más rápida!',
    'install.ios.step1.title': 'Abre Safari',
    'install.ios.step1.desc': 'La instalación PWA solo funciona con Safari en iOS.',
    'install.ios.step2.title': 'Botón Compartir',
    'install.ios.step2.desc': 'Toca el icono de compartir en la parte inferior de la pantalla (cuadrado con flecha).',
    'install.ios.step3.title': 'Añadir a la pantalla de inicio',
    'install.ios.step3.desc': 'Desplázate hacia abajo y toca "Añadir a la pantalla de inicio".',
    'install.ios.step4.title': 'Añadir',
    'install.ios.step4.desc': 'Toca "Añadir" en la esquina superior derecha para confirmar.',
    'install.ios.important': 'Importante para iOS',
    'install.ios.important_desc': 'La instalación en iPhone e iPad requiere Safari. Chrome, Firefox y otros navegadores no soportan esta función en iOS.',
    
    // Footer
    'footer.description': 'Creación de sitios web modernos y bots de Discord personalizados. Transformamos tus ideas en experiencias digitales excepcionales.',
    'footer.quick_links': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.copyright': 'Copyright ©2025 WifiRic. Diseñado por Nathan & Aymeric',
    'footer.support': 'Soporte',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    
    // Language
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.de': 'Deutsch',
    'language.pt': 'Português',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.faq': 'FAQ',
    'nav.contact': 'Kontakt',
    'nav.install': 'Installieren',
    'nav.login': 'Anmelden',
    'nav.profile': 'Profil',
    'nav.admin': 'Verwaltung',
    'nav.logout': 'Abmelden',
    
    // Auth Modal
    'auth.title': 'Anmelden',
    'auth.subtitle': 'Mit Discord anmelden oder registrieren',
    'auth.description': 'Zugriff auf Ihr Profil und Ihre Nachrichten',
    'auth.discord_button': 'Mit Discord anmelden',
    'auth.loading': 'Anmeldung...',
    
    // Hero
    'hero.title': 'WifiRic',
    'hero.subtitle': 'Digitaler Schöpfer',
    'hero.text1': 'Websites angepasst an Ihre Bedürfnisse und Ihr Budget',
    'hero.text2': 'Maßgeschneiderte Discord-Bots für Ihre Bedürfnisse',
    'hero.text3': 'Einzigartige Digitale Erlebnisse',
    'hero.description': 'Wir erstellen Websites oder Discord-Bots nach Ihren Bedürfnissen!',
    'hero.description2': 'Von modernen oder klassischen Websites bis hin zu komplexen Discord-Bots - wir verwandeln Ihre Ideen in Realität.',
    'hero.discord_button': 'Unserem Discord beitreten',
    'hero.services_button': 'Unsere Dienste entdecken',
    
    // Services
    'services.title': 'Unsere Dienste',
    'services.subtitle': 'Komplette digitale Lösungen zur Transformation Ihrer Online-Präsenz',
    'services.web.title': 'Websites',
    'services.web.description': 'Full-Stack Webseitenentwicklung (Front-End und Back-End).',
    'services.bot.title': 'Discord Bots',
    'services.bot.description': 'Erstellung von benutzerdefinierten Discord-Bots zur Automatisierung und Bereicherung Ihrer Community.',
    'services.design.title': 'UI/UX Design',
    'services.design.description': 'Elegante Benutzeroberflächen mit Animationen und Mikro-Interaktionen, sichere und optimierte Websites für das beste Benutzererlebnis',
    'services.cost.title': 'Kosten',
    'services.cost.description': 'Tarife angepasst an Ihre Bedürfnisse, mit wettbewerbsfähigen Preisen für alle Ihre Projekte.',
    
    // Reviews
    'reviews.title': 'Unsere Bewertungen',
    'reviews.subtitle': 'Was unsere Kunden über unsere Arbeit sagen',
    'reviews.filters': 'Filter',
    'reviews.filter_rating': 'Nach Bewertung filtern',
    'reviews.filter_all': 'Alle Bewertungen',
    'reviews.filter_type': 'Nach Projekttyp filtern',
    'reviews.all_types': 'Alle Typen',
    'reviews.website': 'Website',
    'reviews.discord_bot': 'Discord Bot',
    'reviews.other': 'Andere',
    'reviews.clear_filters': 'Filter zurücksetzen',
    'reviews.no_reviews': 'Noch keine Bewertungen',
    'reviews.no_matching': 'Keine Bewertungen entsprechen den ausgewählten Filtern',
    'reviews.be_first': 'Seien Sie der Erste, der eine Bewertung hinterlässt!',
    'reviews.leave_review': 'Bewertung hinterlassen',
    'reviews.login_required': 'Anmelden um eine Bewertung zu hinterlassen',
    'reviews.translate': 'Übersetzen',
    'reviews.translation_error': 'Übersetzungsfehler',
    
    // About
    'about.title': 'WifiRic - Unsere Vision',
    'about.subtitle': 'Bei WifiRic überschreiten wir die Grenzen der Entwicklung, um außergewöhnliche Erlebnisse zu schaffen, die die Zukunft des Webs und der Discord-Communities prägen.',
    'about.web.title': 'Webentwicklung',
    'about.web.description': 'Websites angepasst an Ihre Bedürfnisse und Anfragen, um alles, was Sie sich vorstellen, zum Leben zu erwecken.',
    'about.bot.title': 'Discord Bots',
    'about.bot.description': 'Automatisierung und benutzerdefinierte Funktionen für Ihre Community.',
    'about.design.title': 'Futuristisches Design',
    'about.design.description': 'Elegante Benutzeroberflächen mit Animationen und Mikro-Interaktionen, sichere und optimierte Websites für das beste Benutzererlebnis',
    'about.cost.title': 'Kosten',
    'about.cost.description': 'Tarife angepasst an Ihre Bedürfnisse, mit wettbewerbsfähigen Preisen für alle Ihre Projekte.',
    'about.cta.title': 'Bereit, Ihr Projekt zu transformieren?',
    'about.cta.subtitle': 'Treten Sie unserer Discord-Community bei und entdecken Sie, wie wir Ihnen helfen können, etwas Außergewöhnliches zu schaffen.',
    'about.cta.button': 'Jetzt starten',
    
    // FAQ
    'faq.title': 'Häufig gestellte Fragen',
    'faq.subtitle': 'Finden Sie schnell Antworten auf Ihre Fragen',
    'faq.q1': 'Welche Arten von Websites erstellen Sie?',
    'faq.a1': '//',
    'faq.q2': 'Was kostet eine Website oder ein Discord-Bot?',
    'faq.a2': '//',
    'faq.q3': 'Was ist die Lieferzeit?',
    'faq.a3': '//',
    'faq.q4': 'Bieten Sie Wartung an?',
    'faq.a4': '//',
    'faq.q5': 'Wie funktioniert die Erstellung von Discord-Bots?',
    'faq.a5': '//',
    'faq.q6': 'Akzeptieren Sie Ratenzahlungen?',
    'faq.a6': '//',
    'faq.no_answer': 'Antwort nicht gefunden?',
    'faq.no_answer_subtitle': 'Unser Team ist hier, um alle Ihre spezifischen Fragen zu beantworten',
    'faq.contact_discord': 'Kontaktieren Sie uns auf Discord',
    
    // Contact
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Bereit, Ihr Projekt zu starten? Wir sind hier, um zu helfen',
    'contact.methods': 'Kontaktmethoden',
    'contact.discord_recommended': 'Discord (Empfohlen)',
    'contact.discord_desc': 'Treten Sie unserem Server für sofortigen Support bei',
    'contact.email': 'E-Mail',
    'contact.email_desc': 'Verwenden Sie das Formular unten',
    'contact.why_choose': 'Warum WifiRic wählen?',
    'contact.benefit1': 'Reaktionsschneller und persönlicher Support',
    'contact.benefit2': 'Modernste Technologien',
    'contact.benefit3': 'Garantierte Kundenzufriedenheit',
    'contact.pricing': 'Preise?',
    'contact.pricing1': 'Ihr Website/Discord Bot Angebot ist kostenlos.',
    'contact.pricing2': 'Basierend auf Ihrer Anfrage wird der Preis angepasst.',
    'contact.form.name': 'Name',
    'contact.form.email': 'E-Mail',
    'contact.form.subject': 'Betreff',
    'contact.form.message': 'Nachricht',
    'contact.form.project_type': 'Projekttyp',
    'contact.form.website': 'Website',
    'contact.form.discord_bot': 'Discord Bot',
    'contact.form.both': 'Beide',
    'contact.form.other': 'Andere',
    'contact.form.submit': 'Nachricht senden',
    'contact.form.sending': 'Wird gesendet...',
    'contact.form.success': 'Anfrage erfolgreich gesendet!',
    'contact.form.success_desc': 'Wir antworten innerhalb von 48 Stunden auf unserem Discord: WifiRic',
    'contact.form.error': 'Fehler',
    'contact.form.error_desc': 'Fehler beim Senden der Nachricht. Bitte versuchen Sie es erneut.',
    'contact.login_required': 'Anmeldung erforderlich',
    'contact.login_desc': 'Bitte melden Sie sich mit Ihrem Discord-Konto an, um eine Nachricht zu senden',
    'contact.login_button': 'Mit Discord anmelden',
    'contact.back': 'Zurück',
    'contact.validation.name': 'Name ist erforderlich',
    'contact.validation.email': 'E-Mail ist erforderlich',
    'contact.validation.email_invalid': 'Ungültige E-Mail',
    'contact.validation.subject': 'Betreff ist erforderlich',
    'contact.validation.message': 'Nachricht ist erforderlich',
    
    // Install
    'install.title': 'Installieren',
    'install.subtitle': 'Fügen Sie WifiRic zu Ihrem Startbildschirm hinzu für ein optimales Erlebnis, wie eine echte native App.',
    'install.installed': 'App installiert!',
    'install.installed_desc': 'WifiRic ist bereits auf Ihrem Gerät installiert. Finden Sie es auf Ihrem Startbildschirm.',
    'install.back_home': 'Zurück zur Startseite',
    'install.quick_install': 'Schnelle Installation verfügbar',
    'install.quick_install_desc': 'Ihr Browser unterstützt die automatische Installation. Klicken Sie, um mit einem Klick zu installieren!',
    'install.install_now': 'Jetzt installieren',
    'install.why_install': 'Warum die App installieren?',
    'install.benefit1.title': 'Sofortiges Laden',
    'install.benefit1.desc': 'Die App startet in einem Bruchteil einer Sekunde, ohne auf den Browser zu warten.',
    'install.benefit2.title': 'Offline-Modus',
    'install.benefit2.desc': 'Greifen Sie auf zuvor besuchte Seiten auch ohne Internetverbindung zu.',
    'install.benefit3.title': 'Benachrichtigungen',
    'install.benefit3.desc': 'Erhalten Sie Benachrichtigungen über Neuigkeiten und wichtige Updates.',
    'install.benefit4.title': 'Sicher',
    'install.benefit4.desc': 'HTTPS-Verbindung und geschützte Daten wie auf der Website.',
    'install.guide': 'Installationsanleitung',
    'install.android': 'Android',
    'install.ios': 'iPhone / iPad',
    'install.detected': 'Erkannt:',
    'install.device_ios': 'iOS Gerät (iPhone/iPad)',
    'install.device_android': 'Android Gerät',
    'install.instructions_shown': '- Entsprechende Anweisungen werden unten angezeigt.',
    'install.android.step1.title': 'Chrome öffnen',
    'install.android.step1.desc': 'Stellen Sie sicher, dass Sie Chrome oder einen kompatiblen Browser verwenden.',
    'install.android.step2.title': 'Browser-Menü',
    'install.android.step2.desc': 'Tippen Sie auf die drei Punkte oben rechts im Browser.',
    'install.android.step3.title': 'App installieren',
    'install.android.step3.desc': 'Wählen Sie "App installieren" oder "Zum Startbildschirm hinzufügen".',
    'install.android.step4.title': 'Bestätigen',
    'install.android.step4.desc': 'Tippen Sie im erscheinenden Dialog auf "Installieren".',
    'install.android.tip': 'Tipp',
    'install.android.tip_desc': 'Wenn Sie ein Banner "WifiRic zum Startbildschirm hinzufügen" unten sehen, tippen Sie darauf für eine noch schnellere Installation!',
    'install.ios.step1.title': 'Safari öffnen',
    'install.ios.step1.desc': 'Die PWA-Installation funktioniert nur mit Safari auf iOS.',
    'install.ios.step2.title': 'Teilen-Button',
    'install.ios.step2.desc': 'Tippen Sie auf das Teilen-Symbol unten auf dem Bildschirm (Quadrat mit Pfeil).',
    'install.ios.step3.title': 'Zum Home-Bildschirm',
    'install.ios.step3.desc': 'Scrollen Sie nach unten und tippen Sie auf "Zum Home-Bildschirm".',
    'install.ios.step4.title': 'Hinzufügen',
    'install.ios.step4.desc': 'Tippen Sie oben rechts auf "Hinzufügen" zum Bestätigen.',
    'install.ios.important': 'Wichtig für iOS',
    'install.ios.important_desc': 'Die Installation auf iPhone und iPad erfordert Safari. Chrome, Firefox und andere Browser unterstützen diese Funktion auf iOS nicht.',
    
    // Footer
    'footer.description': 'Erstellung moderner Websites und benutzerdefinierter Discord-Bots. Wir verwandeln Ihre Ideen in außergewöhnliche digitale Erlebnisse.',
    'footer.quick_links': 'Schnelllinks',
    'footer.contact': 'Kontakt',
    'footer.copyright': 'Copyright ©2025 WifiRic. Designed von Nathan & Aymeric',
    'footer.support': 'Support',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Nutzungsbedingungen',
    
    // Language
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.de': 'Deutsch',
    'language.pt': 'Português',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contato',
    'nav.install': 'Instalar',
    'nav.login': 'Entrar',
    'nav.profile': 'Perfil',
    'nav.admin': 'Administração',
    'nav.logout': 'Sair',
    
    // Auth Modal
    'auth.title': 'Entrar',
    'auth.subtitle': 'Entre ou cadastre-se com Discord',
    'auth.description': 'Acesse seu perfil e gerencie suas mensagens',
    'auth.discord_button': 'Entrar com Discord',
    'auth.loading': 'Entrando...',
    
    // Hero
    'hero.title': 'WifiRic',
    'hero.subtitle': 'Criador Digital',
    'hero.text1': 'Sites adaptados às suas necessidades e orçamento',
    'hero.text2': 'Bots Discord personalizados para suas necessidades',
    'hero.text3': 'Experiências Digitais Únicas',
    'hero.description': 'Criamos sites ou bots Discord de acordo com suas necessidades!',
    'hero.description2': 'De sites modernos ou clássicos a bots Discord complexos, transformamos suas ideias em realidade.',
    'hero.discord_button': 'Junte-se ao nosso Discord',
    'hero.services_button': 'Descobrir nossos serviços',
    
    // Services
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Soluções digitais completas para transformar sua presença online',
    'services.web.title': 'Sites',
    'services.web.description': 'Desenvolvimento Full-Stack de sites (Front-End e Back-End).',
    'services.bot.title': 'Bots Discord',
    'services.bot.description': 'Criação de bots Discord personalizados para automatizar e enriquecer sua comunidade.',
    'services.design.title': 'Design UI/UX',
    'services.design.description': 'Interfaces de usuário elegantes com animações e micro-interações, sites seguros e otimizados para a melhor experiência do usuário',
    'services.cost.title': 'Custo',
    'services.cost.description': 'Preços adaptados às suas necessidades, com valores competitivos para todos os seus projetos.',
    
    // Reviews
    'reviews.title': 'Nossas Avaliações',
    'reviews.subtitle': 'O que nossos clientes dizem sobre nosso trabalho',
    'reviews.filters': 'Filtros',
    'reviews.filter_rating': 'Filtrar por nota',
    'reviews.filter_all': 'Todas as notas',
    'reviews.filter_type': 'Filtrar por tipo de projeto',
    'reviews.all_types': 'Todos os tipos',
    'reviews.website': 'Site',
    'reviews.discord_bot': 'Bot Discord',
    'reviews.other': 'Outro',
    'reviews.clear_filters': 'Limpar filtros',
    'reviews.no_reviews': 'Nenhuma avaliação ainda',
    'reviews.no_matching': 'Nenhuma avaliação corresponde aos filtros selecionados',
    'reviews.be_first': 'Seja o primeiro a deixar uma avaliação!',
    'reviews.leave_review': 'Deixar uma avaliação',
    'reviews.login_required': 'Entre para deixar uma avaliação',
    'reviews.translate': 'Traduzir',
    'reviews.translation_error': 'Erro de tradução',
    
    // About
    'about.title': 'WifiRic - Nossa Visão',
    'about.subtitle': 'Na WifiRic, superamos os limites do desenvolvimento para criar experiências excepcionais que moldam o futuro da web e das comunidades Discord.',
    'about.web.title': 'Desenvolvimento Web',
    'about.web.description': 'Sites adaptados às suas necessidades e solicitações, para dar vida a tudo que você imagina.',
    'about.bot.title': 'Bots Discord',
    'about.bot.description': 'Automação e recursos personalizados para sua comunidade.',
    'about.design.title': 'Design Futurista',
    'about.design.description': 'Interfaces de usuário elegantes com animações e micro-interações, sites seguros e otimizados para a melhor experiência do usuário',
    'about.cost.title': 'Custo',
    'about.cost.description': 'Preços adaptados às suas necessidades, com valores competitivos para todos os seus projetos.',
    'about.cta.title': 'Pronto para transformar seu projeto?',
    'about.cta.subtitle': 'Junte-se à nossa comunidade Discord e descubra como podemos ajudá-lo a criar algo extraordinário.',
    'about.cta.button': 'Começar agora',
    
    // FAQ
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Encontre rapidamente respostas para suas perguntas',
    'faq.q1': 'Que tipos de sites vocês criam?',
    'faq.a1': '//',
    'faq.q2': 'Quanto custa um site ou um bot Discord?',
    'faq.a2': '//',
    'faq.q3': 'Qual é o prazo de entrega?',
    'faq.a3': '//',
    'faq.q4': 'Vocês oferecem manutenção?',
    'faq.a4': '//',
    'faq.q5': 'Como funciona a criação de bots Discord?',
    'faq.a5': '//',
    'faq.q6': 'Vocês aceitam pagamento parcelado?',
    'faq.a6': '//',
    'faq.no_answer': 'Não encontrou sua resposta?',
    'faq.no_answer_subtitle': 'Nossa equipe está aqui para responder todas as suas perguntas específicas',
    'faq.contact_discord': 'Contate-nos no Discord',
    
    // Contact
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Pronto para começar seu projeto? Estamos aqui para ajudar',
    'contact.methods': 'Métodos de Contato',
    'contact.discord_recommended': 'Discord (Recomendado)',
    'contact.discord_desc': 'Junte-se ao nosso servidor para suporte instantâneo',
    'contact.email': 'Email',
    'contact.email_desc': 'Use o formulário abaixo',
    'contact.why_choose': 'Por que escolher WifiRic?',
    'contact.benefit1': 'Suporte responsivo e personalizado',
    'contact.benefit2': 'Tecnologias de ponta',
    'contact.benefit3': 'Satisfação do cliente garantida',
    'contact.pricing': 'Preços?',
    'contact.pricing1': 'O orçamento do seu Site/Bot Discord será gratuito.',
    'contact.pricing2': 'Com base na sua solicitação, o preço será ajustado.',
    'contact.form.name': 'Nome',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Assunto',
    'contact.form.message': 'Mensagem',
    'contact.form.project_type': 'Tipo de projeto',
    'contact.form.website': 'Site',
    'contact.form.discord_bot': 'Bot Discord',
    'contact.form.both': 'Ambos',
    'contact.form.other': 'Outro',
    'contact.form.submit': 'Enviar mensagem',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': 'Solicitação enviada com sucesso!',
    'contact.form.success_desc': 'Responderemos em 48 horas no nosso Discord: WifiRic',
    'contact.form.error': 'Erro',
    'contact.form.error_desc': 'Erro ao enviar a mensagem. Por favor, tente novamente.',
    'contact.login_required': 'Login necessário',
    'contact.login_desc': 'Por favor, faça login com sua conta Discord para enviar uma mensagem',
    'contact.login_button': 'Entrar com Discord',
    'contact.back': 'Voltar',
    'contact.validation.name': 'Nome é obrigatório',
    'contact.validation.email': 'Email é obrigatório',
    'contact.validation.email_invalid': 'Email inválido',
    'contact.validation.subject': 'Assunto é obrigatório',
    'contact.validation.message': 'Mensagem é obrigatória',
    
    // Install
    'install.title': 'Instalar',
    'install.subtitle': 'Adicione WifiRic à sua tela inicial para uma experiência ideal, como um aplicativo nativo real.',
    'install.installed': 'App instalado!',
    'install.installed_desc': 'WifiRic já está instalado no seu dispositivo. Encontre-o na sua tela inicial.',
    'install.back_home': 'Voltar ao início',
    'install.quick_install': 'Instalação rápida disponível',
    'install.quick_install_desc': 'Seu navegador suporta instalação automática. Clique para instalar em um clique!',
    'install.install_now': 'Instalar agora',
    'install.why_install': 'Por que instalar o app?',
    'install.benefit1.title': 'Carregamento instantâneo',
    'install.benefit1.desc': 'O app inicia em uma fração de segundo, sem esperar pelo navegador.',
    'install.benefit2.title': 'Modo offline',
    'install.benefit2.desc': 'Acesse páginas visitadas anteriormente mesmo sem conexão com a internet.',
    'install.benefit3.title': 'Notificações',
    'install.benefit3.desc': 'Receba alertas sobre novidades e atualizações importantes.',
    'install.benefit4.title': 'Seguro',
    'install.benefit4.desc': 'Conexão HTTPS e dados protegidos como no site.',
    'install.guide': 'Guia de instalação',
    'install.android': 'Android',
    'install.ios': 'iPhone / iPad',
    'install.detected': 'Detectado:',
    'install.device_ios': 'Dispositivo iOS (iPhone/iPad)',
    'install.device_android': 'Dispositivo Android',
    'install.instructions_shown': '- As instruções correspondentes são mostradas abaixo.',
    'install.android.step1.title': 'Abra o Chrome',
    'install.android.step1.desc': 'Certifique-se de estar usando o Chrome ou um navegador compatível.',
    'install.android.step2.title': 'Menu do navegador',
    'install.android.step2.desc': 'Toque nos três pontos no canto superior direito do navegador.',
    'install.android.step3.title': 'Instalar app',
    'install.android.step3.desc': 'Selecione "Instalar app" ou "Adicionar à tela inicial".',
    'install.android.step4.title': 'Confirmar',
    'install.android.step4.desc': 'Toque em "Instalar" na caixa de diálogo que aparece.',
    'install.android.tip': 'Dica',
    'install.android.tip_desc': 'Se você vir um banner "Adicionar WifiRic à tela inicial" na parte inferior, toque nele para uma instalação ainda mais rápida!',
    'install.ios.step1.title': 'Abra o Safari',
    'install.ios.step1.desc': 'A instalação PWA só funciona com o Safari no iOS.',
    'install.ios.step2.title': 'Botão Compartilhar',
    'install.ios.step2.desc': 'Toque no ícone de compartilhar na parte inferior da tela (quadrado com seta).',
    'install.ios.step3.title': 'Adicionar à tela inicial',
    'install.ios.step3.desc': 'Role para baixo e toque em "Adicionar à Tela de Início".',
    'install.ios.step4.title': 'Adicionar',
    'install.ios.step4.desc': 'Toque em "Adicionar" no canto superior direito para confirmar.',
    'install.ios.important': 'Importante para iOS',
    'install.ios.important_desc': 'A instalação no iPhone e iPad requer o Safari. Chrome, Firefox e outros navegadores não suportam este recurso no iOS.',
    
    // Footer
    'footer.description': 'Criação de sites modernos e bots Discord personalizados. Transformamos suas ideias em experiências digitais excepcionais.',
    'footer.quick_links': 'Links Rápidos',
    'footer.contact': 'Contato',
    'footer.copyright': 'Copyright ©2025 WifiRic. Projetado por Nathan & Aymeric',
    'footer.support': 'Suporte',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    
    // Language
    'language.fr': 'Français',
    'language.en': 'English',
    'language.es': 'Español',
    'language.de': 'Deutsch',
    'language.pt': 'Português',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('wifiric-language');
    if (stored) return stored as Language;
    
    // Auto-detect browser language
    const browserLang = navigator.language.split('-')[0].toLowerCase();
    const supportedLanguages: Language[] = ['fr', 'en', 'es', 'de', 'pt'];
    
    if (supportedLanguages.includes(browserLang as Language)) {
      return browserLang as Language;
    }
    
    return 'fr'; // Default fallback
  });
  const [isTransitioning, setIsTransitioning] = useState(false);

  const setLanguage = useCallback((lang: Language) => {
    if (lang === language) return;
    
    setIsTransitioning(true);
    setLanguageState(lang);
    localStorage.setItem('wifiric-language', lang);
    
    // Quick transition - just enough to be smooth
    setTimeout(() => {
      setIsTransitioning(false);
    }, 150);
  }, [language]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isTransitioning }}>
      <div className={`transition-all duration-150 ease-in-out ${isTransitioning ? 'opacity-95 blur-[1px]' : 'opacity-100 blur-0'}`}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
