// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohsxncrxdqbsuxwybrjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oc3huY3J4ZHFic3V4d3licmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMTE4NDIsImV4cCI6MjA3ODc4Nzg0Mn0.YDKWf6FdWx2VlTLbfxmsTSnYKaLDjreqCQK3QPweYTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});